### PR TITLE
Added searchAppearance as a dimension option

### PR DESCRIPTION
**Pull request by IronistM**
I'd like to filter data on AMP or not. So, I added the `searchAppearance` in the `search_analytics()` as indicated in the documentation of [Search Console API (Search Analytics, Sitemaps, Crawl Errors)](https://developers.google.com/webmaster-tools/search-console-api-original/v3/searchanalytics/query).

Then I can get the expected results like this

`search_analytics(siteURL = "https://www.e-food.gr",searchType = "web",searchAppearance = "AMP_BLUE_LINKS",dimensions = "date",aggregationType = "byPage")`

### CODE REVIEW

**Comment by MarkEdmondson1234** [comment]
Nice, didn't know that was an option now.  Please add yourself to the contributors and add a NEWS item and I'll merge.  Due a new version on CRAN I think to get this out there.

**Comment by andrewm4894** [comment]
This looks like will be quite useful, thanks guys.

**Comment by IronistM** [comment]
BTW, what is going on with the checks? Both failing localy and on travis.

**Comment by MarkEdmondson1234** [comment]
I'm in process of moving tests over to httptest in `googleAuthR`

**Comment by IronistM** [comment]
Ah, cool!

**Comment by MarkEdmondson1234** [comment]
Hey @IronistM I'm getting this error in the test:

` Error: Cannot group by search appearance dimension together with another dimension.`

Can you replicate it?  Does it mean the test should be instead seperated out e.g.

```r
test_that("Can get search analytics data lots of dims with batching", {
  
  sa <- search_analytics(my_example, 
                         dimensions = c("date","device", "country" ,"query","page","searchAppearance"), 
                         walk_data = "byBatch", 
                         rowLimit = 9999)
  
  expect_s3_class(sa, "data.frame")
  
})

test_that("searchAppearance dimension", {
  
  sa <- search_analytics(my_example, 
                         dimensions = c("searchAppearance"))
  
  expect_s3_class(sa, "data.frame")
  
})
```

**Comment by IronistM** [comment]
@MarkEdmondson1234 correct, not everything can be queried with `searchAppearance`. This is not documented however (if I recall correctly) in the documentation.

**Pull request merged**
